// Auto-generated by scripts/sync-characters.mjs
export const CHARACTER_ASSETS = {
  "dancing1": {
    "path": "/characters/dancing1.glb",
    "version": "cb6e43a7"
  },
  "dancing2": {
    "path": "/characters/dancing2.glb",
    "version": "95952cbc"
  },
  "idle": {
    "path": "/characters/idle.glb",
    "version": "fd19e550"
  },
  "kockdown": {
    "path": "/characters/kockdown.glb",
    "version": "20614fb1"
  },
  "running": {
    "path": "/characters/running.glb",
    "version": "3abbda99"
  },
  "walking": {
    "path": "/characters/walking.glb",
    "version": "9f2b4080"
  }
};

export function characterSrc(key) {
  const asset = CHARACTER_ASSETS[key];
  if (!asset) throw new Error(`Unknown character asset: ${key}`);
  return `${asset.path}?v=${asset.version}`;
}
